In [219]:
##
##Script to get List of categories available in Yelp that list restraurants in ranking
##
import pandas as pd
import numpy as np
#for creating geo coordinate combinations
import itertools  as it
from yelpapi import YelpAPI
import requests     # how python goes onto the internet!
import re           # regex
from bs4 import BeautifulSoup # a python HTML parser (version 3)
from urllib2 import Request, urlopen
import json
from pandas.io.json import json_normalize
%matplotlib inline

In [52]:
#https://www.yelp.com/developers/v2/manage_api_keys refresh to generate new keys
api_key = 'SD5ybcet2QSwWXz2N7M5lw'
api_secret = 'EJBXJBAFgEka0br1ynT6HwWJVT8'
access_token = 'EESADq5kSfBL4XkbxzwJxsqhZIgQHbJs'
access_secret = 'JMU-eh8i0eVUUYxJcjelLkZEfTY'

In [53]:
yelp_api = YelpAPI(api_key, api_secret, access_token, access_secret)

In [212]:
def getbiz(nw_latitude, nw_longitude,se_latitude, se_longitude):
    bounds = str(se_latitude)+','+str(se_longitude)+'|'+str(nw_latitude)+','+str(nw_longitude)
    #search_results = yelp_api.search_query(term = 'bar',ll='37.807244, -122.446011')
    search_results = yelp_api.search_query(term= 'bar', bounds=bounds)
    json_normalize(search_results['businesses'])
    #Yelp = Yelp.append(getbiz)

In [96]:
def getbizinfo(businessID)
business_detail = yelp_api.business_query(id=businessID)
json_normalize(business_detail)

In [213]:
#Yelp = getbiz
#Yelp = Yelp.append(getbiz('37.807244', '-122.446011', '37.783661', '-122.385667'))
Yelp = Yelp.append(getbiz(37.807244, -122.446011, 37.783661, -122.385667))

In [250]:
Yelp

categories    display_phone  \
0                                      [[Pubs, pubs]]  +1-415-928-2414   
1                     [[Cocktail Bars, cocktailbars]]  +1-415-744-5000   
2                                      [[Bars, bars]]  +1-415-654-5061   
3            [[Cafes, cafes], [Wine Bars, wine_bars]]  +1-415-634-7002   
4   [[American (Traditional), tradamerican], [Beer...              NaN   
5                            [[Wine Bars, wine_bars]]  +1-415-516-6945   
6                 [[Pubs, pubs], [Beer Bar, beerbar]]  +1-415-660-5142   
7   [[Lounges, lounges], [Cocktail Bars, cocktailb...  +1-415-817-1712   
8   [[Bars, bars], [American (Traditional), tradam...  +1-415-982-8898   
9                     [[Cocktail Bars, cocktailbars]]  +1-415-441-2323   
10  [[Cocktail Bars, cocktailbars], [American (Tra...  +1-415-872-7773   
11                               [[Lounges, lounges]]  +1-415-474-4448   
12  [[American (New), newamerican], [Cocktail Bars...  +1-415-434-4204   
13      [[Pubs, pubs], [Cocktail Bars, cocktailbars]]  +1-415-928-0677   
14  [[Cocktail Bars, cocktailbars], [Lounges, loun...  +1-415-757-0290   
15    [[Gastropubs, gastropubs], [Beer Bar, beerbar]]  +1-415-361-5500   
16  [[Lounges, lounges], [American (New), newameri...  +1-415-617-0071   
17                    [[Cocktail Bars, cocktailbars]]              NaN   
18  [[Sports Bars, sportsbars], [Lounges, lounges]...  +1-415-735-5522   
19               [[Austrian, austrian], [Bars, bars]]  +1-415-474-2000   
0                                      [[Pubs, pubs]]  +1-415-928-2414   
1                     [[Cocktail Bars, cocktailbars]]  +1-415-744-5000   
2                                      [[Bars, bars]]  +1-415-654-5061   
3            [[Cafes, cafes], [Wine Bars, wine_bars]]  +1-415-634-7002   
4   [[American (Traditional), tradamerican], [Beer...              NaN   
5                            [[Wine Bars, wine_bars]]  +1-415-516-6945   
6                 [[Pubs, pubs], [Beer Bar, beerbar]]  +1-415-660-5142   
7   [[Lounges, lounges], [Cocktail Bars, cocktailb...  +1-415-817-1712   
8   [[Bars, bars], [American (Traditional), tradam...  +1-415-982-8898   
9                     [[Cocktail Bars, cocktailbars]]  +1-415-441-2323   
10  [[Cocktail Bars, cocktailbars], [American (Tra...  +1-415-872-7773   
11                               [[Lounges, lounges]]  +1-415-474-4448   
12  [[American (New), newamerican], [Cocktail Bars...  +1-415-434-4204   
13      [[Pubs, pubs], [Cocktail Bars, cocktailbars]]  +1-415-928-0677   
14  [[Cocktail Bars, cocktailbars], [Lounges, loun...  +1-415-757-0290   
15    [[Gastropubs, gastropubs], [Beer Bar, beerbar]]  +1-415-361-5500   
16  [[Lounges, lounges], [American (New), newameri...  +1-415-617-0071   
17                    [[Cocktail Bars, cocktailbars]]              NaN   
18  [[Sports Bars, sportsbars], [Lounges, lounges]...  +1-415-735-5522   
19               [[Austrian, austrian], [Bars, bars]]  +1-415-474-2000   

                                          id  \
0   the-black-horse-london-pub-san-francisco   
1       pacific-cocktail-haven-san-francisco   
2              benjamin-cooper-san-francisco   
3                     bodega-san-francisco-2   
4        hopwater-distribution-san-francisco   
5                  robberbaron-san-francisco   
6                  liquid-gold-san-francisco   
7                      bar-587-san-francisco   
8                the-boardroom-san-francisco   
9                    mezcalito-san-francisco   
10          hos-bootleg-tavern-san-francisco   
11                         rye-san-francisco   
12           barbarossa-lounge-san-francisco   
13                   zekis-bar-san-francisco   
14            topsys-fun-house-san-francisco   
15                     hogwash-san-francisco   
16             comstock-saloon-san-francisco   
17                  hi-lo-club-san-francisco   
18                   jackalope-san-francisco   
19                  leopolds-san-francisco-2   


In [119]:
#arange(-1,1,0.1)
nw_latitude = 37.807244
se_latitude = 37.783661
step = ((nw_latitude+se_latitude)/15)
latitude = np.arange(nw_latitude,se_latitude ,step,dtype = float)

In [120]:
latitude
#np.arange(-1,1,0.1)

array([], dtype=float64)

In [249]:
nw_latitude = 37.807244
se_latitude = 37.783661
step = ((nw_latitude-se_latitude)/15)
a = np.arange(se_latitude, nw_latitude, step)
nw_longitude = -122.446011
se_longitude = -122.385667
step = ((se_longitude-nw_longitude)/15)
b = np.arange(nw_longitude, se_longitude, step)
#>>> list1=['a','b','c']
#>>> list2=[1,2]
#geo = [str(a[0])+',', str(b[0]), str(a[len(a)-1])+','+str(a[len(b)-1])]
#for r in it.product(a, b): geo.insert(r[0] +','+ r[1])
#geo
latitude

array([ 37.783661 ,  37.7852332,  37.7868054,  37.7883776,  37.7899498,
        37.791522 ,  37.7930942,  37.7946664,  37.7962386,  37.7978108,
        37.799383 ,  37.8009552,  37.8025274,  37.8040996,  37.8056718])

('37.783661,', '-122.446011')

In [222]:
#latitude
geo = [zip(x,longitude) for x in it.permutations(latitude,len(longitude))]
geo

KeyboardInterrupt: 

In [163]:
longitude

array([-122.446011  , -122.44198807, -122.43796513, -122.4339422 ,
       -122.42991927, -122.42589633, -122.4218734 , -122.41785047,
       -122.41382753, -122.4098046 , -122.40578167, -122.40175873,
       -122.3977358 , -122.39371287, -122.38968993])

In [173]:
#geo = {'lat': latitude, 'lon':longitude}

In [178]:
geo

[array([-84.66235]),
 array([-84.65832707]),
 array([-84.65430413]),
 array([-84.6502812]),
 array([-84.64625827]),
 array([-84.64223533]),
 array([-84.6382124]),
 array([-84.63418947]),
 array([-84.63016653]),
 array([-84.6261436]),
 array([-84.62212067]),
 array([-84.61809773]),
 array([-84.6140748]),
 array([-84.61005187]),
 array([-84.60602893]),
 array([-84.6607778]),
 array([-84.65675487]),
 array([-84.65273193]),
 array([-84.648709]),
 array([-84.64468607]),
 array([-84.64066313]),
 array([-84.6366402]),
 array([-84.63261727]),
 array([-84.62859433]),
 array([-84.6245714]),
 array([-84.62054847]),
 array([-84.61652553]),
 array([-84.6125026]),
 array([-84.60847967]),
 array([-84.60445673]),
 array([-84.6592056]),
 array([-84.65518267]),
 array([-84.65115973]),
 array([-84.6471368]),
 array([-84.64311387]),
 array([-84.63909093]),
 array([-84.635068]),
 array([-84.63104507]),
 array([-84.62702213]),
 array([-84.6229992]),
 array([-84.61897627]),
 array([-84.61495333]),
 array([-8