In [2]:
import requests
from pprint import pprint

In [3]:
zwsid = 'X1-ZWz1fis6jvgtmz_5jgqp'
zillow = requests.get('http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=X1-ZWz1fis6jvgtmz_5jgqp&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA')

In [4]:
zillow.content

'<?xml version="1.0" encoding="utf-8"?><SearchResults:searchresults xsi:schemaLocation="http://www.zillow.com/static/xsd/SearchResults.xsd http://www.zillowstatic.com/vstatic/70a941d/static/xsd/SearchResults.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SearchResults="http://www.zillow.com/static/xsd/SearchResults.xsd"><request><address>2114 Bigelow Ave</address><citystatezip>Seattle, WA</citystatezip></request><message><text>Request successfully processed</text><code>0</code></message><response><results><result><zpid>48749425</zpid><links><homedetails>http://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/</homedetails><graphsanddata>http://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/#charts-and-data</graphsanddata><mapthishome>http://www.zillow.com/homes/48749425_zpid/</mapthishome><comparables>http://www.zillow.com/homes/comps/48749425_zpid/</comparables></links><address><street>2114 Bigelow Ave N</stre

In [5]:
zillow = requests.get('http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=X1-ZWz1fis6jvgtmz_5jgqp&citystatezip=94107')

In [6]:
zillow.text

u'<?xml version="1.0" encoding="utf-8"?><SearchResults:searchresults xsi:schemaLocation="http://www.zillow.com/static/xsd/SearchResults.xsd http://www.zillowstatic.com/vstatic/70a941d/static/xsd/SearchResults.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SearchResults="http://www.zillow.com/static/xsd/SearchResults.xsd"><request><address></address><citystatezip>94107</citystatezip></request><message><text>Error: no address specified</text><code>500</code></message></SearchResults:searchresults><!-- H:001  T:1ms  S:150  R:Tue Nov 15 17:35:54 PST 2016  B:5.0.36246-master.60030c1~hotfix_pre.654883f -->'

In [7]:
import numpy as np
np.arange(1.2,20+0.4, 0.4)

array([  1.2,   1.6,   2. ,   2.4,   2.8,   3.2,   3.6,   4. ,   4.4,
         4.8,   5.2,   5.6,   6. ,   6.4,   6.8,   7.2,   7.6,   8. ,
         8.4,   8.8,   9.2,   9.6,  10. ,  10.4,  10.8,  11.2,  11.6,
        12. ,  12.4,  12.8,  13.2,  13.6,  14. ,  14.4,  14.8,  15.2,
        15.6,  16. ,  16.4,  16.8,  17.2,  17.6,  18. ,  18.4,  18.8,
        19.2,  19.6,  20. ])

In [22]:
#Specify the lat lon to specify bounds
nw_latitude=37.810298
nw_longitude=-122.522450
se_latitude=37.704093
se_longitude=-122.375803
block = 2

increment_lat = (nw_latitude-se_latitude)/block
increment_lon = (nw_longitude-se_longitude)/block

#Find latitude and longitude blocks coordinates
lat = np.arange(se_latitude-increment_lat, nw_latitude, increment_lat)
lon = np.arange(se_longitude-increment_lon, nw_longitude, increment_lon)



In [23]:
lat

array([ 37.6509905,  37.704093 ,  37.7571955])

In [24]:
lon

array([-122.3024795, -122.375803 , -122.4491265])

In [25]:
import itertools
listoflist = lat,lon

#make all combinations of bounds required for calculation
comb  = list(itertools.product(*listoflist))

#sequence the list of coordinates to run north (east to west) to south (east to west)
comb = comb[::-1]
    


In [26]:
comb

[(37.757195500000002, -122.44912650000001),
 (37.757195500000002, -122.375803),
 (37.757195500000002, -122.3024795),
 (37.704093, -122.44912650000001),
 (37.704093, -122.375803),
 (37.704093, -122.3024795),
 (37.650990499999999, -122.44912650000001),
 (37.650990499999999, -122.375803),
 (37.650990499999999, -122.3024795)]

In [ ]:
    i=0
    bounds = []
    #print (block*(block-1)-1)
    while i<=(block*(block-1)-1):
    #while i<=block*block:
        if rem(i,block) != (block-1):
            bounds = bounds + [str(comb[i][0])+','+str(comb[i][1])+'|'+str(comb[i+1+block][0])+','+str(comb[i+1+block][1])]
            #print len(bounds)
            i += 1
        elif rem(i,block) == (block-1):
            i += 1
    return bounds;


